const FASHION_TERMS = [
     { term: "Aksesoris (Aksesoris)", definition: "Hiasan atau tambahan pada pakaian untuk meningkatkan penampilan." },
  { term: "Alta Moda (Mode Tinggi)", definition: "Istilah Italia untuk mode haute couture atau busana kelas atas." },
  { term: "Atasan (Atasan)", definition: "Bagian atas pakaian, seperti kemeja atau blus." },
  { term: "Aksen (Aksen)", definition: "Penekanan pada bagian tertentu dari pakaian untuk meningkatkan penampilan." },
  { term: "Asesori (Asesoris)", definition: "Sama dengan aksesoris, yaitu hiasan atau tambahan pada pakaian." },
  { term: "Atribut (Atribut)", definition: "Ciri atau karakteristik yang membedakan suatu pakaian atau gaya." },
  { term: "Aksentuasi (Penekanan)", definition: "Penekanan pada bagian tertentu dari pakaian untuk meningkatkan penampilan." },
  { term: "Alta Costura", definition: "Istilah Italia untuk haute couture atau busana kelas atas yang dibuat dengan teknik dan bahan berkualitas tinggi." },
  { term: "Artistikn(Artistik)", definition: "Berkaitan dengan seni dan kreativitas dalam desain busana." },
  { term: "Arah (Arah)", definition: "Arah atau orientasi dalam desain busana, seperti arah garis atau bentuk." },
  { term: "Asimilasi (Asimilasi)", definition: "Proses penyesuaian atau penggabungan elemen-elemen desain busana." },
  { term: "Adaptasi (Adaptasi)", definition: "Proses penyesuaian desain busana untuk kebutuhan atau situasi tertentu." },
  { term: "Aplikasi (Aplikasi)", definition: "Proses penambahan elemen-elemen desain pada pakaian, seperti bordir atau patch." },
  { term: "Anyaman (Anyaman)", definition: "Teknik pembuatan kain atau kerajinan dengan menggunakan benang atau bahan lainnya." },
  { term: "Awet (Tahan Lama)", definition: "Kemampuan pakaian untuk tetap dalam kondisi baik setelah digunakan dalam waktu lama." },
  { term: "Anti Kerut (Anti Kerut)", definition: "Teknologi atau perawatan yang digunakan untuk mengurangi kerutan pada pakaian." },
  { term: "Anti Susut (Anti Susut)", definition: "Teknologi atau perawatan yang digunakan untuk mengurangi penyusutan pada pakaian." },
  { term: "Asli (Asli)", definition: "Bahan atau produk yang tidak dipalsukan atau diimpor." },
  { term: "Art Deco (Art Deco)", definition: "Gaya desain yang populer pada tahun 1920-an hingga 1940-an, ditandai dengan bentuk geometris dan ornamen yang mewah." },
  { term: "Avant-garde", definition: "Gaya desain yang inovatif dan eksperimental, sering kali menantang norma-norma konvensional." },
  { term: "Atelier (Studio)", definition: "Tempat kerja desainer busana atau pengrajin pakaian." },
  { term: "Alta Moda Italia", definition: "Istilah yang merujuk pada mode haute couture Italia." },
  { term: "Aksentuasi Warna", definition: "Penggunaan warna untuk menekankan atau menonjolkan bagian tertentu dari pakaian." },
  { term: "Atribut Pakaian", definition: "Ciri atau karakteristik yang membedakan suatu pakaian, seperti label atau logo." },
  { term: "Aksesoris Fashion", definition: "Hiasan atau tambahan pada pakaian yang digunakan untuk meningkatkan penampilan." },
  { term: "Teknologi Tinggi", definition: "Teknologi canggih yang digunakan dalam industri busana, seperti teknologi tekstil atau produksi." },
  { term: "Artwear", definition: "Pakaian yang dirancang dengan sentuhan artistik atau kreatif." },
  { term: "Activewear* (", definition: "Pakaian yang dirancang untuk kegiatan olahraga atau aktivitas fisik." },
  { term: "Athleisure", definition: "Gaya busana yang memadukan elemen olahraga dan santai." },
  { term: "Desain Aksesoris", definition: "Desain aksesoris atau hiasan yang digunakan pada pakaian." },
  { term: "Baju", definition: "Pakaian penutup tubuh bagian atas, biasanya berlengan." },
  { term: "Blazer", definition: "Jaket semi formal yang dikenakan di luar kemeja." },
  { term: "Bros", definition: "Perhiasan kecil yang disematkan pada pakaian." },
  { term: "Belt", definition: "Ikat pinggang untuk mengencangkan atau menghias pakaian." },
  { term: "Bolero", definition: "Jaket pendek tanpa kancing, biasanya dipakai untuk melengkapi gaun." },
  { term: "Bustier", definition: "Pakaian wanita ketat menutup dada hingga pinggang, membentuk siluet tubuh." },
  { term: "Balotelli", definition: "Jenis kain tekstil halus dan jatuh, banyak digunakan untuk busana muslim." },
  { term: "Brokat", definition: "Kain bermotif rumit yang ditenun dengan benang emas, perak, atau warna lain." },
  { term: "Baskin", definition: "Tambahan kain atau hiasan pada bagian pinggang baju atau gaun." },
  { term: "Balutan", definition: "Cara melilitkan kain pada tubuh sebagai gaya busana." },
  { term: "Bordir", definition: "Hiasan kain atau pakaian yang dibuat dengan sulaman benang." },
  { term: "Benang", definition: "Serat panjang hasil pintalan kapas, wol, atau lainnya untuk menjahit/menenun." },
  { term: "Baggy", definition: "Model celana longgar lebar di bagian paha." },
  { term: "Ball gown", definition: "Gaun pesta panjang dengan bagian bawah mengembang." },
  { term: "Beret", definition: "Topi bundar pipih, biasanya terbuat dari wol." },
  { term: "Blangkon", definition: "Penutup kepala tradisional Jawa dari lipatan kain." },
  { term: "Batikwan", definition: "Perajin atau pembuat batik." },
  { term: "Buckle", definition: "Pengait atau kepala ikat pinggang." },
  { term: "Bodice", definition: "Bagian atas gaun yang menutupi dada sampai pinggang." },
  { term: "Bias", definition: "Potongan kain menyerong serat untuk hasil jatuh kain yang indah." },
  { term: "Bale", definition: "Bal kain yang digulung atau dilipat untuk dijual." },
  { term: "Bridal", definition: "Segala sesuatu yang berkaitan dengan busana pengantin." },
  { term: "Bust line", definition: "Garis rancangan pakaian yang mengikuti bentuk dada." },
  { term: "Backstitch", definition: "Jenis jahitan mesin/jahit tangan yang kuat untuk menyambung kain." },
  { term: "Basting", definition: "Jahitan sementara (tack) untuk menahan potongan kain sebelum dijahit permanen." },
  { term: "Beads", definition: "Manik-manik kecil untuk hiasan busana." },
  { term: "Binding", definition: "Kain kecil atau pita untuk menutup tepi pakaian agar rapi." },
  { term: "Belt loop", definition: "Lingkaran kecil pada celana atau rok tempat menyelipkan ikat pinggang." },
  { term: "Boning", definition: "Bahan penguat pada korset atau bustier agar bentuk tetap tegak." },
  { term: "Brocade", definition: "Kain tenun bermotif timbul dengan hiasan benang emas/perak." },
  { term: "Bloomer", definition: "Celana longgar wanita, biasanya dipakai sebagai pakaian dalam atau olahraga zaman dahulu." },
  { term: "Batik printing", definition: "Kain bermotif batik hasil cetakan mesin." },
  { term: "Batik lukis", definition: "Batik yang dibuat dengan teknik melukis langsung pada kain." },
  { term: "Bust dart", definition: "Lipat kecil pada pakaian di sekitar dada untuk menyesuaikan bentuk tubuh." },
  { term: "Button", definition: "Kancing sebagai pengikat pakaian." },
  { term: "Buttonhol", definition: "Lubang pada pakaian tempat memasukkan kancing." },
  { term: "Back opening", definition: "Bukaan pada bagian belakang pakaian, biasanya untuk gaun." },
  { term: "Batik tulis", definition: "Batik tradisional yang dibuat dengan tangan menggunakan canting." },
  { term: "Bias tape", definition: "Pita kain dari potongan serong yang dipakai untuk menutup tepi kain." },
  { term: "Bergo", definition: "Jilbab instan dengan pet di bagian kepala, banyak dipakai sehari-hari." },
  { term: "Cape", definition: "busana terbuka di bagian lengan yang menggantung dari bahu." },
  { term: "Cap Sleeve", definition: "desain lengan pendek yang hanya menutupi bagian bahu." },
  { term: "Casing", definition: "lipatan kain yang digunakan untuk memasukkan tali atau karet." },
  { term: "Casual", definition: "gaya berpakaian yang santai." },
  { term: "Catalogue", definition: "sekumpulan contoh desain atau koleksi busana." },
  { term: "Catwalk", definition: "lintasan untuk pertunjukan busana di acara mode." },
  { term: "Checkered", definition: "pola kain dengan desain berbentuk kotak." },
  { term: "Celana", definition: "pakaian bagian bawah yang menutupi area pinggang sampai kaki." },
  { term: "Cembung", definition: "bentuk desain busana yang melengkung ke luar." },
  { term: "Center Back (CB)", definition: "garis utama pada bagian belakang busana." },
  { term: "Center Front (CF)", definition: "garis utama pada bagian depan busana." },
  { term: "Chanel Jacket", definition: "desain jaket klasik dengan potongan yang simpel." },
  { term: "Chiffon", definition: "jenis kain yang tipis, ringan, dan transparan." },
  { term: "Chintz", definition: "kain katun yang bermotif bunga dengan permukaan mengkilap." },
  { term: "Cire", definition: "kain yang mengalami pelapisan lilin sehingga berkilau." },
  { term: "Classic Style", definition: "gaya busana yang tetap relevan sepanjang waktu." },
  { term: "Clasp", definition: "pengait kecil yang digunakan untuk menutup pakaian." },
  { term: "Cloth", definition: "istilah umum yang merujuk pada kain." },
  { term: "Clothing", definition: "semua jenis pakaian secara keseluruhan." },
  { term: "Clutch", definition: "tas kecil yang tidak memiliki tali." },
  { term: "Cocktail Dress", definition: "gaun yang dipakai untuk acara semi-formal." },
  { term: "Collar", definition: "bagian kerah yang terdapat pada pakaian." },
  { term: "Color Blocking", definition: "cara mengkombinasikan warna-warna kontras dalam satu pakaian." },
  { term: "Combination", definition: "penggabungan dua atau lebih bahan atau warna." },
  { term: "Comfort", definition: "rasa nyaman saat mengenakan pakaian." },
  { term: "Contemporary Style", definition: "gaya busana modern yang sesuai dengan tren terkini." },
  { term: "Contrast", definition: "perbedaan antara warna atau pola untuk mempertegas desain." },
  { term: "Corsage", definition: "bunga kecil yang dihias, biasanya dipasangkan pada pakaian." },
  { term: "Corset (Korset)", definition: "pakaian dalam yang digunakan untuk memperindah bentuk tubuh." },
  { term: "Couture (Haute Couture)", definition: "busana desain khusus dengan tingkat jahitan yang tinggi." },
  { term: "Dandy", definition: "Gaya busana pria abad ke-18/19 yang elegan, rapi, dan penuh detail." },
  { term: "Damaged jeans", definition: "Jeans dengan efek robek atau usang (distressed)." },
  { term: "Damask", definition: "Kain jacquard bermotif timbul, biasanya dipakai untuk busana formal." },
  { term: "Day dress", definition: "Gaun untuk pemakaian sehari-hari." },
  { term: "Decolleté", definition: "Garis leher rendah yang menonjolkan dada." },
  { term: "Decoupage", definition: "Teknik menghias kain atau busana dengan menempelkan motif." },
  { term: "Debutante dress", definition: "Gaun pesta resmi yang dipakai saat perkenalan sosial." },
  { term: "Deconstructed", definition: "Gaya desain busana dengan tampilan unfinished atau tidak sempurna." },
  { term: "Demi-couture", definition: "Koleksi busana setengah couture, lebih eksklusif dari ready-to-wear." },
  { term: "Demi-season coat", definition: "Mantel ringan untuk musim transisi (gugur/semi)." },
  { term: "Demi-wedge", definition: "Model  sepatu hak wedge pendek." },
  { term: "Denim", definition: "Kain katun tebal dengan anyaman twill, identik dengan jeans." },
  { term: "Designer label", definition: "Merek atau busana yang dibuat oleh desainer ternama." },
  { term: "Detachable collar", definition: "Kerah tambahan yang bisa dilepas." },
  { term: "Diamond neckline", definition: "Garis leher berbentuk belah ketupat." },
  { term: "Diamond quilt", definition: "Jahitan quilt dengan pola belah ketupat." },
  { term: "Digital print", definition: "Motif pada kain yang dicetak dengan printer digital." },
  { term: "Diagonal weave", definition: "Anyaman kain miring (twill weave)." },
  { term: "Dirndl", definition: "Pakaian tradisional Jerman/Austria dengan blus, gaun, dan apron." },
  { term: "Dirndl skirt", definition: "Rok lebar berlipit, bagian dari busana dirndl." },
  { term: "Disco pants", definition: "Celana ketat mengilap yang populer di era 1970-an." },
  { term: "Distressed", definition: "Efek usang, pudar, atau robek pada kain, biasanya denim." },
  { term: "Dogtooth check", definition: "Motif kotak kecil menyerupai houndstooth." },
  { term: "Dolce & Gabbana style", definition: "Estetika desain khas rumah mode Dolce & Gabbana." },
  { term: "Dolce Vita style", definition: "Gaya glamor Italia tahun 1960-an." },
  { term: "Dolman sleeve", definition: "Model lengan longgar yang menyatu dengan badan pakaian." },
  { term: "Dome bag", definition: "Tas tangan dengan bentuk melengkung menyerupai kubah." },
  { term: "Double-breasted", definition: "Model jas dengan dua baris kancing depan." },
  { term: "Double knit", definition: "Kain rajut tebal dengan dua sisi sama." },
  { term: "Dobby weave", definition: "Kain bermotif kecil hasil mesin dobby." },
  { term: "Dock shoe", definition: "Sepatu kasual dengan sol karet, mirip boat shoes." },
  { term: "Dog collar", definition: "Kalung choker lebar, sering digunakan sebagai aksesori fashion." },
  { term: "D’Orsay", definition: "Model sepatu dengan sisi terbuka, hanya menutupi ujung kaki dan tumit." },
  { term: "D’Orsay flat", definition: "Sepatu flat model d’Orsay." },
  { term: "D’Orsay pump", definition: "Sepatu hak tinggi model d’Orsay." },
  { term: "Drawstring", definition: "Tali serut untuk mengencangkan busana atau tas." },
  { term: "Drawstring bag", definition: "Tas serut dengan tali di bagian atas." },
  { term: "Draped skirt", definition: "Rok dengan lipatan draperi menjuntai." },
  { term: "Draping", definition: "Teknik membentuk desain dengan kain langsung di atas mannequin." },
  { term: "Drill", definition: "Kain katun tebal, sering dipakai untuk seragam atau kerja." },
  { term: "Driving shoe", definition: "Sepatu slip-on dengan sol karet fleksibel, nyaman untuk mengemudi." },
  { term: "Drip hem", definition: "Model keliman rok atau gaun yang tidak rata." },
  { term: "Duchesse satin", definition: "Kain satin mewah, tebal, dan mengilap." },
  { term: "Duck cloth", definition: "Kain kanvas katun berat dan kuat." },
  { term: "Duffle coat", definition: "Jaket wol dengan kancing toggle dan hoodie." },
  { term: "Duvet coat", definition: "Jaket bulu tebal menyerupai selimut." },
  { term: "Dye", definition: "Pewarna kain atau tekstil." },
  { term: "Dip dye", definition: "Teknik pewarnaan gradasi pada kain atau busana." },
  { term: "Drum dyeing", definition: "Teknik pewarnaan kain dalam drum besar." },
  { term: "Dress", definition: "Gaun terusan wanita." },
  { term: "Dress boots", definition: "Sepatu boot dengan model formal." },
  { term: "Dress shirt", definition: "Kemeja formal dengan kerah, biasa dipakai dengan jas." },
  { term: "Dungaree", definition: "Celana overall berbahan denim." },
  { term: "Drop shoulder", definition: "Potongan lengan yang jatuh melewati bahu." },
  { term: "Drop waist", definition: "Potongan busana dengan garis pinggang jatuh lebih rendah." },
  { term: "Elegan", definition: "Bersifat anggun dan berkelas dalam berpakaian." },
  { term: "Eksklusif", definition: "Produk fashion yang dibuat terbatas dengan kualitas tinggi" },
  { term: "Elastis", definition: "kain atau bahan yang lentur dan dapat kembali ke bentuk semula." },
  { term: "Embos", definition: "teknik memberi tekstur timbul pada kain." },
  { term: "Ecoprint", definition: "teknik cetak kain menggunakan daun/bunga alami." },
  { term: "Etisilk", definition: "sutra hasil pengolahan ramah lingkungan." },
  { term: "Eco-dye", definition: "pewarna alami ramah lingkungan." },
  { term: "Embroidery yarn", definition: "benang khusus sulaman." },
  { term: "Embroidery lace", definition: "renda hasil bordiran." },
  { term: "Etnik textile", definition: "kain bermotif tradisional khas suku tertentu." },
  { term: "Eksposur", definition: "penonjolan detail tertentu dalam desain." },
  { term: "Eksperimen", definition: "uji coba desain baru." },
  { term: "Eklektik", definition: "gaya campuran dari berbagai tren." },
  { term: "Ear cuff", definition: "perhiasan telinga tanpa tindikan." },
  { term: "Earring", definition: "anting-anting." },
  { term: "Eksklusifitas", definition: "kesan terbatas dan prestisius." },
  { term: "Empire dress", definition: "gaun dengan garis pinggang tinggi." },
  { term: "Empire waist", definition: "potongan busana di bawah dada." },
  { term: "Estetika", definition: "Nilai keindahan yang diperhatikan dalam desain fashion." },
  { term: "Etalase", definition: "Tempat memajang produk fashion." },
  { term: "Etnik", definition: "Motif atau gaya yang berasal dari tradisi budaya tertentu." },
  { term: "Eco-friendly", definition: "Bahan atau produk ramah lingkungan." },
  { term: "Eping", definition: "Jarum pentul untuk menjepit kain saat menjahit." },
  { term: "Ekuator", definition: "Bagian tengah pola untuk menyesuaikan ukuran." },
  { term: "Eyelash lace", definition: "Renda dengan bentuk seperti bulu mata" },
  { term: "Edge stitching", definition: "Jahitan dekat tepi kain untuk rapi" },
  { term: "Eyelet", definition: "Lubang kecil yang diperkuat untuk tali sepatu atau tali pakaian" },
  { term: "E-stitch", definition: "Jenis jahitan khusus pada mesin jahit" },
  { term: "E-sketch", definition: "Sketsa desain digital fashion" },
  { term: "E-pattern cutting", definition: "Pemotongan pola menggunakan teknologi" },
  { term: "Evase", definition: "Bentuk pakaian melebar ke bawah" },
  { term: "Efek kilap", definition: "tampilan mengilap pada kain karena teknik tenun atau finishing." },
  { term: "Elastic thread", definition: "benang karet elastis untuk smock." },
  { term: "Ekspos raw edge", definition: "busana dengan tepi kain dibiarkan terbuka." },
  { term: "Embellished dress", definition: "busana berhias payet, manik, atau bordir." },
  { term: "Etnik modern", definition: "gaya fashion etnik dikombinasikan dengan sentuhan modern." },
  { term: "Exotic bag", definition: "tas dari kulit eksotis (ular, buaya, dll)." },
  { term: "Eksperimen motif", definition: "pencampuran motif berbeda dalam fashion." },
  { term: "Elastic knitwear", definition: "Pakaian rajut yang elastis" },
  { term: "Embossing heat press", definition: "Mesin tekan panas untuk emboss." },
  { term: "Event wear", definition: "Pakaian untuk acara khusus." },
  { term: "applique", definition: "Pakaian untuk acara khusus." },
  { term: "E-wax print", definition: "Cetak kain dengan teknologi lilin elektronik" },
  { term: "Enzyme wash", definition: "Proses pencucian kain untuk efek khusus" },
  { term: "External pocket", definition: "Kantong luar baju." },
  { term: "Edge space", definition: "Jarak antara jahitan dan tepi kain." },
  { term: "Epauliere", definition: "Kecepatan peregangan kain" },
  { term: "Epi knot", definition: "Teknik ikatan pada aksesoris tali" },
  { term: "Epicenter", definition: "Titik fokus desain fashion" },
  { term: "Efloral", definition: "Motif bunga yang rumit" },
  { term: "Fabric", definition: "Bahan kain utama yang digunakan untuk membuat pakaian." },
  { term: "Feather", definition: "Bulu yang digunakan sebagai hiasan pada aksesoris atau gaun pesta." },
  { term: "Fiber", definition: "Serat dasar dari bahan alami atau sintetis yang membentuk kain." },
  { term: "Finish", definition: "Penyelesaian akhir pada kain, seperti hem atau edging untuk tampilan rapi." },
  { term: "Fit", definition: "Ukuran dan bentuk pakaian yang sesuai dengan tubuh pemakai." },
  { term: "Flange", definition: "Lipatan atau pinggiran dekoratif pada lengan atau kerah." },
  { term: "Flannel", definition: "Kain wol lembut yang hangat, sering untuk kemeja atau celana panjang." },
  { term: "Flare", definition: "Bentuk melebar pada bagian bawah rok atau celana untuk efek dramatis." },
  { term: "Flat Fell Seam", definition: "Jahitan datar yang kuat, sering digunakan pada jeans atau pakaian outdoor." },
  { term: "Fleece", definition: "Kain lembut berbulu seperti wol sintetis, untuk sweater atau jaket hangat." },
  { term: "French Cuff", definition: "Lengan kemeja yang dilipat dan dikaitkan dengan manset ganda." },
  { term: "French Seam", definition: "Jahitan rapi yang menyembunyikan tepi kain, untuk tampilan bersih." },
  { term: "Full Bust", definition: "Desain khusus untuk payudara penuh, dengan dart atau pleat untuk kenyamanan." },
  { term: "Fusible Interfacing", definition: "Kain penyangga yang direkatkan dengan panas untuk memperkuat struktur pakaian." },
  { term: "Fashion", definition: "Tren dan gaya pakaian secara keseluruhan dalam industri mode." },
  { term: "Fashionista", definition: "Penggemar fashion yang mengikuti tren secara aktif." },
  { term: "Fedora", definition: "Topi lebar tepi dengan mahkota rendah, ikon gaya klasik." },
  { term: "Femme", definition: "Gaya feminin yang menekankan kelembutan dan keanggunan." },
  { term: "Festive Wear", definition: "Pakaian untuk acara pesta, seperti gaun berkilau." },
  { term: "Figure", definition: "Bentuk tubuh yang menjadi dasar desain pola pakaian." },
  { term: "Flat Pattern", definition: "Pola datar yang dibuat sebelum dipotong kain." },
  { term: "Flex Fabric", definition: "Kain elastis yang fleksibel untuk pakaian olahraga." },
  { term: "Floral Print", definition: "Motif bunga pada kain untuk gaya musim semi." },
  { term: "Flowy", definition: "Gaya longgar dan mengalir, seperti dress bohemian." },
  { term: "Fashion Forward", definition: "Gaya inovatif yang memimpin tren masa depan." },
  { term: "Fabric Manipulation", definition: "Teknik memanipulasi kain seperti pleating atau gathering." },
  { term: "Fitted Silhouette", definition: "Bentuk pakaian yang menempel ketat pada tubuh untuktampilan ramping." },
  { term: "Gala Dress", definition: "Gaun formal yang dikenakan pada acara resmi atau pesta malam." },
  { term: "Gaucho Pants", definition: "Celana lebar yang terinspirasi dari pakaian tradisional peternak di Amerika Selatan." },
  { term: "Gauffered", definition: "Kain yang memiliki tekstur bergelombang atau berlipit." },
  { term: "Gauze", definition: "Kain tipis dan ringan yang sering digunakan untuk pakaian musim panas." },
  { term: "Gauze Blouse", definition: "Blus yang terbuat dari kain gauze, cocok untuk cuaca panas." },
  { term: "Gauze Cape", definition: "Jubah atau cape yang terbuat dari kain gauze, memberikan efek transparan dan elegan." },
  { term: "Gauze Dress", definition: "Gaun yang terbuat dari kain gauze, ringan dan transparan." },
  { term: "Gauze Fabric", definition: "Kain tipis dan ringan yang sering digunakan untuk pakaian musim panas." },
  { term: "Gauze Overlay", definition: "Lapisan kain gauze yang diletakkan di atas kain lain sebagai dekorasi." },
  { term: "Gauze Scarf", definition: "Syal yang terbuat dari kain gauze, ringan dan transparan." },
  { term: "Gauze Skirt", definition: "Rok yang terbuat dari kain gauze, memberikan kesan ringan dan mengalir." },
  { term: "Gauze Tunic", definition: "Tunik yang terbuat dari kain gauze, nyaman dan ringan." },
  { term: "Gauze Wrap", definition: "Pakaian atau aksesori yang dibungkus dengan kain gauze." },
  { term: "Gathering", definition: "Teknik menjahit dengan mengerutkan kain untuk memberikan efek volume." },
  { term: "Gingham", definition: "Kain kotak-kotak yang biasanya berwarna putih dan satu warna lain, sering digunakan untuk pakaian kasual." },
  { term: "Gingham Dress", definition: "Gaun yang terbuat dari kain gingham dengan motif kotak-kotak." },
  { term: "Gilet", definition: "Rompi tanpa lengan yang biasanya dipakai sebagai lapisan tambahan." },
  { term: "Glam Rock", definition: "Gaya busana yang menggabungkan elemen glamor dan rock, sering dengan pakaian berkilau dan aksesoris mencolok." },
  { term: "Glamorous Fabric", definition: "Kain yang memiliki kilau atau efek mewah seperti satin atau velvet." },
  { term: "Glamour", definition: "Gaya busana yang menonjolkan kemewahan dan daya tarik visual." },
  { term: "Gloves", definition: "Sarung tangan yang digunakan sebagai aksesori atau pelindung tangan." },
  { term: "Godet", definition: "Potongan kain segitiga yang disisipkan pada rok atau gaun untuk memberikan volume dan bentuk melebar." },
  { term: "Gorget", definition: "Aksesori leher yang biasanya berupa kerah dekoratif." },
  { term: "Gown", definition: "Gaun panjang yang biasanya dikenakan pada acara formal." },
  { term: "Grainline", definition: "Arah serat kain yang harus diperhatikan saat memotong pola agar pakaian tidak melar atau berubah bentuk." },
  { term: "Greige", definition: "Kain yang belum diwarnai atau diproses, berwarna abu-abu atau krem." },
  { term: "Graphic Print", definition: "Motif cetak dengan desain grafis yang mencolok dan modern." },
  { term: "Grosgrain", definition: "Jenis pita kain dengan tekstur bergaris-garis yang sering digunakan sebagai hiasan pada pakaian atau aksesori." },
  { term: "Gusset", definition: "Potongan kain berbentuk segitiga atau berlian yang disisipkan pada pakaian untuk memberikan ruang gerak lebih." },
  { term: "Gusseted Sleeve", definition: "Lengan pakaian yang memiliki potongan kain tambahan untuk memperluas ruang gerak." },
  { term: "Habutai", definition: "kain sutra tipis dan halus, sering dipakai untuk lining." },
  { term: "Habutai silk", definition: "sebutan lain dari kain sutra habutai." },
  { term: "Hessian", definition: "kain goni dari serat kasar, biasa untuk dekorasi." },
  { term: "Houndstooth", definition: "motif kain berbentuk kotak bergerigi seperti gigi anjing." },
  { term: "Herringbone", definition: "motif tenunan zig-zag menyerupai tulang ikan herring." },
  { term: "Heather fabric", definition: "kain dengan warna bercampur sehingga tampak bertekstur." },
  { term: "Hopsack", definition: "kain dengan tenunan kotak-kotak agak longgar." },
  { term: "Hem", definition: "keliman, lipatan tepi kain agar tidak bertiras." },
  { term: "Hand stitch", definition: "jahitan yang dibuat dengan tangan." },
  { term: "Hemline", definition: "garis bawah pakaian (panjang rok atau celana)." },
  { term: "Hook and eye", definition: "kancing kait kecil (pengait & lubang)." },
  { term: "Hand embroidery", definition: "sulaman yang dibuat dengan tangan." },
  { term: "Hidden zipper", definition: "resleting yang tersembunyi di dalam jahitan." },
  { term: "Honeycomb smocking", definition: "teknik kerutan kain membentuk pola sarang lebah." },
  { term: "High waist", definition: "potongan pakaian dengan pinggang tinggi." },
  { term: "Hip dart", definition: "lipit jahitan di pinggang/panggul untuk membentuk siluet." },
  { term: "Half-back stitch", definition: "jenis tusuk jelujur setengah panjang." },
  { term: "Hot fix", definition: "aplikasi hiasan (misal rhinestone) dengan alat pemanas." },
  { term: "Halterneck", definition: "model leher pakaian dengan tali melingkar di leher." },
  { term: "House dress", definition: "gaun sederhana untuk dipakai di rumah." },
  { term: "Hot pants", definition: "celana sangat pendek." },
  { term: "High heels", definition: "sepatu dengan hak tinggi." },
  { term: "High-low dress", definition: "gaun dengan bagian depan lebih pendek daripada belakang." },
  { term: "Hoodie", definition: "jaket atau sweater bertudung." },
  { term: "Hoop skirt", definition: "rok lebar dengan rangka lingkaran di dalamnya." },
  { term: "Harem pants", definition: "celana longgar dengan kerutan di pergelangan." },
  { term: "High fashion / Haute couture", definition: "mode kelas tinggi dengan pengerjaan eksklusif." },
  { term: "Hipster pants", definition: "celana dengan potongan rendah di pinggul." },
  { term: "H-line skirt", definition: "rok lurus berbentuk huruf H." },
  { term: "Hat", definition: "topi." },
  { term: "Hairpin", definition: "jepit rambut." },
  { term: "Handbag", definition: "tas tangan." },
  { term: "Headband", definition: "ikat kepala." },
  { term: "Hoop earrings", definition: "anting besar berbentuk lingkaran." },
  { term: "Hand gloves", definition: "sarung tangan." },
  { term: "Headdress", definition: "hiasan kepala (modern maupun tradisional)." },
  { term: "Heat transfer vinyl (HTV)", definition: "bahan sablon tekstil yang ditempel dengan panas." },
  { term: "Holographic fabric", definition: "kain dengan efek kilau pelangi." },
  { term: "Heavy satin", definition: "satin tebal dengan kilau elegan." },
  { term: "Handloom fabric", definition: "kain hasil tenunan tangan." },
  { term: "Hemstitch", definition: "tusuk hias dengan celah di tepi kain." },
  { term: "Hook and loop (Velcro)", definition: "perekat tekstil berbasis kait dan loop." },
  { term: "Hand quilting", definition: "teknik menjahit lapisan kain dengan tangan." },
  { term: "Heat sealing", definition: "teknik merekatkan bahan dengan panas." },
  { term: "Half lining", definition: "pelapis bagian dalam pakaian yang hanya setengah." },
  { term: "H-line dress", definition: "gaun lurus tanpa bentuk pinggang menonjol." },
  { term: "Hip-length jacket", definition: "jaket dengan panjang sampai panggul." },
  { term: "High collar", definition: "kerah tinggi menutupi leher." },
  { term: "Henley shirt", definition: "kaus dengan kancing pendek di dada tanpa kerah." },
  { term: "Handkerchief hem", definition: "potongan bawah rok/gaun asimetris menyerupai sapu tangan." },
  { term: "Illustrasi mode", definition: "Gambar rancangan busana sebelum diwujudkan." },
  { term: "Inner", definition: "Pakaian lapisan dalam untuk kenyamanan atau menutup bahan tipis." },
  { term: "Inset", definition: "Potongan kain tambahan pada pakaian untuk dekorasi atau keleluasaan." },
  { term: "Interlining", definition: "Lapisan di antara kain luar dan furing untuk menambah struktur." },
  { term: "Interfacing", definition: "Bahan pelapis pada bagian busana agar bentuk lebih tegas." },
  { term: "Invisible zipper", definition: "Resleting tersembunyi yang tidak terlihat dari luar." },
  { term: "Inverted pleat", definition: "Lipit kain yang dilipat ke arah dalam." },
  { term: "Industrial sewing machine", definition: "Mesin jahit industri untuk produksi massal." },
  { term: "Iridescent fabric", definition: "Kain dengan efek kilau berubah warna dari sudut berbeda." },
  { term: "Inkjet printing on fabric", definition: "Teknik cetak kain dengan printer digital." },
  { term: "Indian sari", definition: "Pakaian tradisional India berupa kain panjang dililitkan." },
  { term: "Inlay", definition: "Tambahan kain pada pola untuk memberi kelonggaran jahitan." },
  { term: "Inset pocket", definition: "Saku yang dijahit masuk ke dalam sehingga rata dari luar." },
  { term: "Italian cut", definition: "Potongan pakaian ramping dan elegan khas Italia." },
  { term: "Irish lace", definition: "Jenis renda tradisional dari Irlandia." },
  { term: "Inspiration board", definition: "Papan referensi ide untuk desain busana." },
  { term: "Ironing", definition: "Proses menyetrika kain agar rapi sebelum/ setelah dijahit." },
  { term: "Iron-on patch", definition: "Aplikasi/tempelan kain yang direkatkan dengan panas setrika." },
  { term: "Inventory", definition: "Daftar stok kain, bahan, atau aksesori busana." },
  { term: "Inverted collar", definition: "Model kerah dengan lipatan ke arah dalam." },
  { term: "Insert trim", definition: "Tambahan hiasan (renda/pita) yang disisipkan pada busana." },
  { term: "Inside seam", definition: "Jahitan bagian dalam pakaian yang tidak tampak dari luar." },
  { term: "In-seam pocket", definition: "Saku yang tersembunyi di dalam garis jahitan samping." },
  { term: "Italian shoes", definition: "Sepatu bergaya Italia, dikenal elegan dan mewah." },
  { term: "Indigo dye", definition: "Pewarna alami berwarna biru tua, banyak digunakan pada denim." },
  { term: "Illusion Neckline", definition: "Potongan leher baju dengan kain transparan (biasanya tulle atau mesh) yang memberi ilusi leher terbuka namun tetap tertutup." },
  { term: "Inseam", definition: "Jahitan pada bagian dalam celana, dari selangkangan hingga ujung kaki." },
  { term: "Interlining", definition: "Lapisan kain tambahan di antara kain utama dan furing, biasanya untuk memberi struktur pada pakaian." },
  { term: "Iridescent", definition: "Kain atau material yang warnanya berubah-ubah ketika terkena cahaya, memberi efek pelangi atau shimmering." },
  { term: "Ivy Cap", definition: "Topi datar klasik dengan visor pendek di depan, populer di Eropa." },
  { term: "Item Statement", definition: "Satu elemen busana atau aksesori yang mencuri perhatian dan menjadi pusat gaya dalam sebuah outfit." },
  { term: "Jabot", definition: "Hiasan lipit kain atau renda yang dipasang di bagian depan blus/kemeja, biasanya memberi kesan klasik." },
  { term: "Jacquard", definition: "Jenis kain tenun dengan motif timbul yang dibuat dengan alat tenun khusus (Jacquard loom)." },
  { term: "Jacket", definition: "Pakaian luar dengan bukaan depan (resleting atau kancing), berfungsi melindungi tubuh sekaligus bergaya." },
  { term: "Jade Green", definition: "Istilah warna hijau lembut seperti batu giok, sering dipakai dalam deskripsi warna fashion." },
  { term: "Jali-Jali", definition: "Motif atau pola berlubang (openwork) pada kain, bisa dibuat dengan rajutan, renda, atau teknik laser cut." },
  { term: "Jamawar", definition: "Kain mewah dari India dengan motif tradisional, biasanya tenun brokat atau jacquard." },
  { term: "Japanese Denim", definition: "Denim berkualitas tinggi dari Jepang, terkenal kuat dan bertekstur unik." },
  { term: "Japara Fabric", definition: "Kain asal Jepara dengan motif batik khas, digunakan untuk busana maupun dekorasi." },
  { term: "Jeans", definition: "Celana atau pakaian dari kain denim, ikon fashion kasual." },
  { term: "Jegging", definition: "Celana ketat menyerupai legging tetapi berbahan denim elastis." },
  { term: "Jersey", definition: "Kain rajut elastis, banyak digunakan untuk kaos, dress, hingga sportswear." },
  { term: "Jewelry", definition: "Perhiasan seperti kalung, cincin, gelang, dan anting yang melengkapi busana." },
  { term: "Jewel Neckline", definition: "Model kerah bulat tinggi mendekati leher, sering digunakan pada dress." },
  { term: "Jewel Tone", definition: "Istilah warna cerah dan mewah terinspirasi dari batu mulia (emerald, ruby, sapphire)." },
  { term: "Jibbah", definition: "Jubah panjang longgar, pakaian tradisional dari Timur Tengah." },
  { term: "Jilbab", definition: "Pakaian penutup kepala hingga dada yang biasa dipakai muslimah." },
  { term: "Jive Style", definition: "Gaya busana yang terinspirasi dari tarian jive (1940-an), penuh warna dan energik." },
  { term: "Jobber", definition: "Penjual grosir kain atau pakaian sisa produksi, populer dalam industri fashion." },
  { term: "Jogger Pants", definition: "Celana kasual dengan karet di pergelangan kaki, nyaman untuk santai atau olahraga." },
  { term: "Join Seam", definition: "Jahitan sambungan antara dua potong kain." },
  { term: "Jodhpurs", definition: "Celana panjang ketat di betis namun longgar di paha, awalnya dipakai untuk menunggang kuda." },
  { term: "Joker Necklace (atau Choker)", definition: "Kalung ketat melingkar di leher, sering menjadi tren fashion." },
  { term: "Jolly Roger Print", definition: "Motif dengan lambang bajak laut (tengkorak & tulang bersilang), kadang dipakai dalam fashion edgy." },
  { term: "Jouy Print (Toile de Jouy)", definition: "Motif kain asal Prancis bergambar pemandangan atau adegan pastoral." },
  { term: "Jumpsuit", definition: "Busana one-piece yang menyatukan atasan dan celana." },
  { term: "Junk Fashion", definition: "Fashion yang dibuat dari bahan daur ulang atau limbah (upcycling)." },
  { term: "Jute", definition: "Serat alami dari tanaman rami, sering dipakai untuk aksesori atau tas etnik." },
  { term: "Jewel Embellishment", definition: "Hiasan pada busana menggunakan batu imitasi atau kristal." },
  { term: "Jersey Dress", definition: "Gaun berbahan jersey yang jatuhnya lembut dan elastis." },
  { term: "Juliet Sleeve", definition: "Model lengan baju dengan bagian atas menggembung dan bawahnya ketat, terinspirasi busana renaisans." },
  { term: "Kaftan", definition: "Pakaian longgar berbentuk jubah, biasanya dipakai santai atau pesta." },
  { term: "Kangaroo pocket", definition: "Saku besar di bagian depan hoodie/sweater, terbuka dari kedua sisi." },
  { term: "Kapri pants (Capri)", definition: "Celana sepanjang betis atau sedikit di bawah lutut." },
  { term: "Kebaya", definition: "Blus tradisional Indonesia yang pas badan, dipadukan dengan kain batik/songket." },
  { term: "Keffiyeh", definition: "Syal kotak-kotak khas Timur Tengah, juga jadi aksesori fashion modern." },
  { term: "Kimono", definition: "Jubah panjang tradisional Jepang, kini sering diadaptasi jadi busana modern." },
  { term: "Kilt", definition: "Rok lipit tradisional Skotlandia dengan motif tartan." },
  { term: "Knitwear", definition: "Busana berbahan rajut, seperti sweater, cardigan, scarf." },
  { term: "Knickerbockers", definition: "Celana longgar sebatas lutut, populer awal abad ke-20." },
  { term: "Knife pleats", definition: "Lipit kain tajam mengarah satu sisi, sering pada rok." },
  { term: "Knitted dress", definition: "Gaun berbahan rajut elastis yang mengikuti bentuk tubuh." },
  { term: "Knot bag", definition: "Tas tangan kecil ditutup dengan simpul." },
  { term: "Kurta", definition: "Tunik panjang tradisional India/Pakistan dengan celana longgar." },
  { term: "Kashmir (Cashmere)", definition: "Kain wol halus dari bulu kambing Kashmir." },
  { term: "Kawaii style", definition: "Gaya Jepang imut dengan warna pastel & aksesori lucu." },
  { term: "Kempis heel", definition: "Sepatu hak rendah mendatar, lebih tebal dari flat shoes." },
  { term: "Kitten heels", definition: "Sepatu hak kecil (2–4 cm), feminin tapi tetap nyaman." },
  { term: "Knotting technique", definition: "Teknik simpul pada tekstil, rajut, atau aksesori." },
  { term: "Knit stitch", definition: "Jahitan dasar pada kain rajut" },
  { term: "Knit binding", definition: "Teknik penyelesaian tepi kain rajut agar tidak melar." },
  { term: "Kelim", definition: "Jahitan lipatan di tepi kain agar tidak terurai (hem)." },
  { term: "Kick pleat", definition: "Lipit tambahan di rok bagian belakang/samping agar mudah melangkah." },
  { term: "Keyhole neckline", definition: "Potongan leher berbentuk lubang kecil (seperti kunci)." },
  { term: "Knit-in pattern", definition: "Motif dekoratif yang dibuat langsung saat proses merajut." },
  { term: "Kente cloth", definition: "Kain tenun tradisional Ghana dengan warna cerah dan motif geometris" },
  { term: "Kersey", definition: "Kain wol tebal dengan permukaan halus, sering dipakai untuk coat" },
  { term: "Kid leather", definition: "Kulit lembut dari kambing muda, digunakan untuk sarung tangan atau Sepatu" },
  { term: "Kick tape", definition: "Pita tambahan pada bagian bawah rok atau mantel untuk memperkuat kelim" },
  { term: "Knit gauge", definition: "Ukuran kepadatan rajutan pada kain knit." },
  { term: "Knurling detail", definition: "Tekstur kecil-kecil timbul pada logam/perhiasan fashion." },
  { term: "Lace", definition: "Kain tipis berenda yang sering digunakan dalam gaun dan aksesori." },
  { term: "Lagenlook", definition: "Gaya berpakaian yang menekankan lapisan dan bentuk longgar, sering kali dengan potongan asimetris." },
  { term: "Lapel", definition: "Bagian yang menonjol di sisi kerah pakaian, biasanya pada jas atau blazer." },
  { term: "Leggings", definition: "Celana ketat yang terbuat dari bahan elastis, nyaman dipakai untuk aktivitas sehari-hari." },
  { term: "Linen", definition: "Kain ringan dan bernapas yang terbuat dari serat rami, cocok untuk cuaca panas." },
  { term: "Longline", definition: "Desain pakaian yang lebih panjang dari biasanya, sering ditemukan pada jaket atau atasan." },
  { term: "Lumberjack shirt", definition: "Kemeja flanel kotak-kotak yang terinspirasi dari pakaian pekerja hutan." },
  { term: "Lurex", definition: "Serat yang mengandung metalik, sering digunakan untuk memberi efek berkilau pada kain." },
  { term: "Lapel pin", definition: "Aksesori kecil yang dipasang pada lapel jas, sering kali sebagai bentuk pernyataan gaya atau dukungan." },
  { term: "Lycra", definition: "Serat elastis yang sering digunakan dalam pakaian olahraga dan pakaian ketat." },
  { term: "Loungewear", definition: "Pakaian santai yang nyaman, seperti piyama atau setelan rumah." },
  { term: "Long skirt", definition: "Rok panjang yang biasanya menjuntai hingga pergelangan kaki." },
  { term: "Layering", definition: "Teknik berpakaian dengan mengenakan beberapa lapisan pakaian untuk menciptakan tampilan yang menarik." },
  { term: "Leather", definition: "Bahan kulit yang sering digunakan untuk jaket, tas, dan sepatu." },
  { term: "Lace-up", definition: "Desain dengan tali atau ikatan, sering ditemukan pada sepatu dan atasan." },
  { term: "Little black dress (LBD)", definition: "Gaun hitam sederhana yang dianggap sebagai item wajib dalam lemari pakaian wanita." },
  { term: "Loafers", definition: "Sepatu tanpa tali yang nyaman, sering kali dengan desain klasik." },
  { term: "Luxe", definition: "Istilah yang digunakan untuk menggambarkan pakaian atau aksesori yang mewah dan berkualitas tinggi." },
  { term: "Lapel collar", definition: "Kerah dengan detail lapel, sering ditemukan pada blazer dan jaket." },
  { term: "Lattice", definition: "Desain kain yang memiliki pola bersilang, sering digunakan pada gaun atau aksesori." },
  { term: "Luxe", definition: "Istilah untuk pakaian atau aksesori yang terlihat mewah dan berkualitas tinggi." },
  { term: "Layered dress", definition: "Gaun yang dirancang dengan beberapa lapisan bahan untuk tampilan yang dinamis." },
  { term: "Leather jacket", definition: "Jaket yang terbuat dari kulit, sering dianggap sebagai item klasik dalam fashion." },
  { term: "Lapel shirt", definition: "Kemeja dengan kerah lapel, sering dipakai dalam situasi semi-formal." },
  { term: "Luxe athleisure", definition: "Pakaian olahraga yang juga dirancang untuk tampilan stylish, cocok untuk kegiatan sehari-hari." },
  { term: "Long sleeve", definition: "Pakaian dengan lengan panjang, memberikan perlindungan lebih pada lengan." },
  { term: "Luxe fabric", definition: "Kain berkualitas tinggi yang sering digunakan dalam koleksi fashion premium." },
  { term: "Leg warmers", definition: "Aksesori yang dikenakan di sekitar kaki, sering digunakan dalam gaya olahraga atau retro." },
  { term: "Lounge set", definition: "Setelan pakaian santai yang terdiri dari atasan dan bawahan, nyaman untuk bersantai di rumah." },
  { term: "Luxury brand", definition: "Merek fashion yang dikenal dengan produk-produk berkualitas tinggi dan harga premium." },
  { term: "Magnet Jarum", definition: "Alat berbentuk magnet kecil yang digunakan untuk mengumpulkan jarum atau peniti agar tidak berserakan." },
  { term: "Manekin", definition: "Boneka tiruan berbentuk tubuh manusia yang digunakan sebagai media untuk memasang, memajang, atau membentuk busana." },
  { term: "Manik-manik", definition: "Aksesori kecil berbentuk bulat atau berbagai bentuk lain dari kaca, plastik, kayu, atau logam, digunakan untuk hiasan pada busana atau aksesori." },
  { term: "Manset", definition: "Bagian ujung lengan baju yang dilapisi atau diberi lipatan khusus agar lebih rapi dan kokoh." },
  { term: "Marker Kain", definition: "Alat tulis khusus untuk memberi tanda atau garis pada kain/pola, biasanya tintanya bisa hilang setelah dicuci atau disetrika." },
  { term: "Meja Pola", definition: "Meja kerja datar yang digunakan untuk menggambar pola, memotong kain, atau merancang busana." },
  { term: "Meja Setrika", definition: "Meja khusus dengan permukaan datar dan tahan panas yang digunakan sebagai alas saat menyetrika pakaian." },
  { term: "Mesin Bordir", definition: "Mesin khusus untuk membuat hiasan berupa bordiran pada kain dengan menggunakan benang berwarna." },
  { term: "Mesin Jahit", definition: "Alat utama dalam menjahit yang berfungsi untuk menyatukan potongan kain dengan benang secara cepat, rapi, dan kuat." },
  { term: "Mesin Uap Mini", definition: "Alat setrika modern yang mengeluarkan uap panas untuk merapikan busana dengan cepat tanpa merusak bahan." },
  { term: "Meteran", definition: "Alat ukur berbentuk pita panjang fleksibel yang digunakan untuk mengukur tubuh, kain, atau pola." },
  { term: "Mini Hanger", definition: "Gantungan kecil untuk menyimpan atau memajang aksesori atau busana dalam ukuran tertentu." },
  { term: "Mirror (Kaca Busana)", definition: "Cermin besar yang digunakan untuk melihat penampilan busana ketika dipakai atau saat fitting." },
  { term: "Mistar", definition: "Alat berbentuk garis lurus dari plastik, kayu, atau logam yang digunakan untuk menggambar pola atau membuat garis lurus pada kain/pola." },
  { term: "Model", definition: "Contoh rancangan pakaian yang dijadikan acuan atau orang yang memperagakan busana di panggung peragaan (fashion show)." },
  { term: "Mode", definition: "Tren atau gaya berpakaian yang berkembang pada suatu masa, dipengaruhi oleh" },
  { term: "Motif", definition: "Pola atau gambar hiasan pada kain atau busana, bisa berupa geometris, floral, batik, atau abstrak." },
  { term: "Motif Kertas", definition: "Pola atau rancangan pakaian yang digambar di atas kertas pola sebagai panduan dalam memotong kain." },
  { term: "Mukena", definition: "Busana muslim khusus wanita yang digunakan untuk beribadah salat, biasanya terdiri dari atasan dan bawahan." },
  { term: "Muslin", definition: "Jenis kain tipis dari katun yang biasa digunakan untuk membuat contoh pola (toile)" },
  { term: "Nappa Leather", definition: "Kulit halus dari domba atau kambing yang lembut, lentur, dan sering digunakan pada jaket, tas, serta sarung tangan." },
  { term: "Navy", definition: "Warna biru gelap menyerupai seragam angkatan laut, populer dalam busana formal dan kasual." },
  { term: "Neckline", definition: "Potongan atau bentuk garis leher pada pakaian, misalnya V-neck, U-neck, boat neck." },
  { term: "Needlework", definition: "Keterampilan menjahit, menyulam, atau menghias kain dengan jarum dan benang." },
  { term: "Negligee", definition: "Pakaian tidur wanita yang ringan, tipis, dan biasanya terbuat dari satin, sutra, atau renda." },
  { term: "Net Fabric", definition: "Kain berongga menyerupai jaring, sering dipakai untuk gaun pesta, kerudung, dan dekorasi busana." },
  { term: "Neutral Colors", definition: "Warna-warna netral seperti putih, hitam, abu-abu, krem, dan cokelat yang mudah dipadukan." },
  { term: "Nylon", definition: "Serat sintetis ringan, kuat, elastis, dan tahan lama, banyak digunakan pada pakaian olahraga, kaos kaki, serta outerwear." },
  { term: "Nehru Jacket", definition: "Jaket bergaya India dengan kerah tegak (mandarin collar), biasanya digunakan untuk busana formal pria." },
  { term: "Notions", definition: "Perlengkapan kecil dalam menjahit seperti kancing, ritsleting, benang, pita, dan karet." },
  { term: "Netted Veil", definition: "Aksesori kepala dari kain jaring halus yang biasanya dipakai bersama topi atau sebagai hiasan gaun pesta." },
  { term: "Nappa Finish", definition: "Finishing kain atau kulit yang membuat permukaan halus, lembut, dan berkilau." },
  { term: "Nap", definition: "Arah serat atau permukaan kain beludru, suede, atau kain berbulu lainnya yang berpengaruh pada kilau kain." },
  { term: "Natural Waistline", definition: "Garis pinggang alami pada tubuh, sering dijadikan acuan potongan busana untuk menonjolkan siluet." },
  { term: "Netted Skirt", definition: "Rok yang dibuat dari kain jaring atau tulle, memberikan efek bervolume." },
  { term: "Normcore", definition: "Tren fashion dengan gaya sederhana, minimalis, dan biasa yang justru menjadi ciri khas." },
  { term: "Nouveau (Art Nouveau Style)", definition: "Gaya seni dan desain akhir abad ke-19 yang memengaruhi motif busana, dengan ciri garis lengkung organik dan dekoratif." },
  { term: "Nursing Wear", definition: "Pakaian khusus ibu menyusui yang didesain praktis dengan bukaan tersembunyi." },
  { term: "Nappa Gloves", definition: "Sarung tangan dari kulit nappa yang elegan, lembut, dan sering digunakan dalam fashion musim dingin." },
  { term: "Nightwear", definition: "Pakaian yang digunakan untuk tidur, seperti piyama, nightdress, atau negligee." },
  { term: "Obi", definition: "Sabuk lebar tradisional Jepang yang digunakan untuk mengikat kimono atau yukata." },
  { term: "Off-shoulder", definition: "Model pakaian dengan bagian bahu terbuka." },
  { term: "Overall", definition: "Pakaian terusan (baju dan celana menyatu), sering digunakan sebagai busana kasual atau kerja." },
  { term: "Oversize", definition: "Gaya pakaian yang dibuat lebih besar dari ukuran tubuh pemakainya untuk memberi kesan longgar." },
  { term: "Overlay", definition: "Lapisan kain tambahan di atas kain utama, biasanya dari bahan transparan seperti tulle atau organza." },
  { term: "Oxford shoes", definition: "Sepatu formal pria/wanita dengan tali, klasik dan elegan." },
  { term: "Oxford cloth", definition: "Jenis kain katun dengan anyaman basket-weave, sering dipakai untuk kemeja." },
  { term: "Ornament", definition: "Hiasan atau aksesori tambahan pada pakaian, tas, atau sepatu." },
  { term: "Organza", definition: "Kain tipis, kaku, dan transparan, sering dipakai untuk gaun pesta." },
  { term: "Opaque tights", definition: "Stocking atau legging tebal dengan serat rapat sehingga tidak tembus pandang." },
  { term: "Opera gloves", definition: "Sarung tangan panjang hingga siku atau lebih, biasanya dipakai dengan gaun malam." },
  { term: "Open-toe shoes", definition: "Sepatu dengan bagian depan terbuka sehingga jari kaki terlihat." },
  { term: "Outfit", definition: "Satu set pakaian lengkap yang dipadukan untuk dikenakan." },
  { term: "Outerwear", definition: "Pakaian luar seperti jaket, mantel, coat, atau cardigan." },
  { term: "Outseam", definition: "Jahitan pada bagian samping luar celana." },
  { term: "Overcoat", definition: "Mantel panjang tebal yang dikenakan di luar pakaian untuk menghangatkan tubuh." },
  { term: "Overdress", definition: "Gaun atau pakaian luar yang dipakai menutupi pakaian dalam." },
  { term: "Overlock", definition: "Teknik jahitan tepi kain dengan mesin obras agar tidak mudah terurai." },
  { term: "Overstitch", definition: "Jahitan hias atau penguat di bagian tepi pakaian." },
  { term: "Ombre", definition: "Efek gradasi warna pada kain, rambut, atau aksesori dari gelap ke terang atau sebaliknya." },
  { term: "Off-duty look", definition: "Gaya santai para model di luar panggung runway, biasanya simpel dan kasual." },
  { term: "Office wear", definition: "Pakaian kerja formal atau semi-formal yang digunakan di kantor." },
  { term: "Outseam piping", definition: "Detail garis tambahan pada sisi luar celana atau rok untuk aksen dekoratif." },
  { term: "Overdye", definition: "Teknik pewarnaan ulang kain untuk menghasilkan warna unik atau lebih pekat." },
  { term: "Overlapping", definition: "Teknik desain pakaian dengan bagian kain yang saling menumpuk." },
  { term: "Orchid color", definition: "Warna ungu muda cerah menyerupai bunga anggrek, populer dalam fashion." },
  { term: "Off-white", definition: "Warna putih gading atau putih tulang yang sering digunakan dalam gaun pengantin." },
  { term: "Opera coat", definition: "Mantel panjang elegan yang biasanya dipakai ke acara formal seperti opera." },
  { term: "Oxford bag trousers", definition: "Celana longgar dengan potongan sangat lebar, populer di era 1920-an." },
  { term: "Outback hat", definition: "Topi bergaya koboi atau safari, populer di Australia." },
  { term: "Pattern (Pola)", definition: "Sebuah desain yang dicetak, dijahit, atau ditenun oleh pabrik dengan pola dekorasi yang sama atau berulang." },
  { term: "Peek-a-boo", definition: "Bagian dari pakaian yang telah dipotong-potong atau sengaja disobek untuk menampilkan bagian badan tertentu atau pakaian bagian dalam." },
  { term: "Petticoat", definition: "Pakaian untuk dijadikan dalaman yang digunakan oleh wanita ketika akan menggunakan gaun, rok, atau sari." },
  { term: "Plaid", definition: "Sebuah motif kain wol dengan blok warna horizontal dan vertical yang berulang sehingga membentuk pola seperti garis." },
  { term: "Pleats", definition: "Sebuah model dengan banyak lipatan-lipatan kain." },
  { term: "Pockets", definition: "Bagian dari pakaian yang berfungsi untuk menampung atau membawa benda yang berukuran kecil." },
  { term: "Poncho", definition: "Bagian luar dari pakaian berbentuk seperti kain yang terbuka yang berfungsi sebagai penutup kepala atau lengan." },
  { term: "Pret-a-Porter", definition: "Desain pakaian yang dijual dalam ukuran standar (S, M, L)." },
  { term: "Print", definition: "Desain yang diaplikasikan pabrik dengan menekankan pola yang sudah dicetak ke dalam kain seperti katun, sutra, atau polyester." },
  { term: "Pullover", definition: "Sebuah pakaian yang cara pamakaiannya dimasukkan melalui kepala. Seperti jumper atau sweater." },
  { term: "Payet", definition: "hiasan kecil berkilau yang dijahit pada kain untuk mempercantik busana." },
  { term: "Puring", definition: "kain bagian dalam yang dipasang agar busana lebih rapi dan nyaman." },
  { term: "Plisket", definition: "lipatan kain kecil-kecil pada rok atau busana (sering disebut pleats)." },
  { term: "Pendedel", definition: "alat untuk membuka jahitan yang salah (seam ripper)." },
  { term: "Permukaan kain", definition: "sisi luar kain yang tampak ketika busana selesai dibuat." },
  { term: "Perca", definition: "sisa-sisa kain kecil dari proses pembuatan busana." },
  { term: "Puring stretch", definition: "jenis kain pelapis yang elastis." },
  { term: "Piyama", definition: "Pakaian tidur yang digunakan saat istirahat malam" },
  { term: "Parka", definition: "Jaket panjang dengan hoodie, cocok untuk cuaca dingin" },
  { term: "Patchwork", definition: "Hiasan atau kain yang terdiri dari potongan-potongan kain berbeda" },
  { term: "Peplum", definition: "Bagian rok atau kain yang melebar di pinggang sebagai hiasan" },
  { term: "Placket", definition: "Bagian pembuka pakaian biasanya di depan seperti kancing atau resleting" },
  { term: "Puff Sleeve", definition: "Lengan baju model mengembang seperti puff" },
  { term: "Quilt", definition: "Teknik menjahit beberapa lapisan kain dengan bantalan di antaranya, biasanya digunakan untuk jaket, rok, atau tas." },
  { term: "Quilting", definition: "Proses atau teknik pembuatan quilt dengan pola jahitan dekoratif." },
  { term: "Quilted Jacket", definition: "Jaket dengan lapisan quilt yang berisi bantalan sehingga hangat dan bertekstur timbul." },
  { term: "Quilted Bag", definition: "Tas dengan tekstur quilt, populer pada brand Chanel." },
  { term: "Quartz Color", definition: "Warna fashion yang terinspirasi dari batu kuarsa, biasanya bernuansa pink pucat atau bening keabu-abuan." },
  { term: "Quilted Skirt", definition: "Rok dengan teknik quilting, memberi kesan tebal dan berstruktur." },
  { term: "Quilted Shoes", definition: "Sepatu dengan detail jahitan quilt untuk memberi tekstur elegan." },
  { term: "Quilted Fabric", definition: "Bahan kain yang dibuat dengan teknik quilting, digunakan untuk outerwear." },
  { term: "Quilted Vest", definition: "Rompi dengan lapisan quilt yang sering dipakai untuk gaya kasual." },
  { term: "Quilt Lining", definition: "Lapisan dalam pakaian dengan teknik quilt untuk kenyamanan dan kehangatan." },
  { term: "Quotidian Style", definition: "Gaya busana sehari-hari yang simpel dan praktis." },
  { term: "Quirky Fashion", definition: "Gaya busana yang unik, eksentrik, dan tidak biasa." },
  { term: "Quilt Pattern", definition: "Motif jahitan dekoratif pada kain quilt (misalnya diamond, kotak, zigzag)." },
  { term: "Quilted Coat", definition: "Mantel dengan lapisan quilt, populer untuk musim dingin." },
  { term: "Quality Fabric", definition: "Istilah untuk bahan tekstil dengan mutu tinggi." },
  { term: "Quarter Sleeve", definition: "Lengan pakaian dengan panjang sekitar seperempat lengan (3/4 sleeve)." },
  { term: "Quarter Brogue", definition: "Model sepatu kulit dengan hiasan lubang (brogue) hanya di ujung depan." },
  { term: "Quarter Panel", definition: "Bagian samping sepatu yang menghubungkan vamp dan heel." },
  { term: "Quilted Texture", definition: "Tekstur timbul dari quilting yang memberi kesan mewah." },
  { term: "Quirky Accessories", definition: "Aksesori dengan desain unik dan nyentrik." },
  { term: "Quintessential Look", definition: "Tampilan fashion yang dianggap paling mewakili suatu gaya tertentu." },
  { term: "Quirky Prints", definition: "Motif kain dengan desain lucu, nyeleneh, atau eksentrik." },
  { term: "Quality Control (QC) Fashion", definition: "Tahap pengecekan kualitas dalam industri fashion agar produk sesuai standar." },
  { term: "Quick-Change Outfit", definition: "Busana yang dirancang untuk cepat diganti (sering dipakai dalam fashion show)." },
  { term: "Quilted Hand Gloves", definition: "Sarung tangan dengan bahan quilted untuk musim dingin." },
  { term: "Rabat", definition: "Lipatan kain yang dijahit atau dijepit sebagai hiasan." },
  { term: "Raffia", definition: "Serat alami atau sintetis yang dipakai untuk membuat tas, topi, atau aksesori." },
  { term: "Raglan", definition: "Model lengan yang jahitannya miring dari kerung leher ke ketiak." },
  { term: "Rajut", definition: "Teknik membuat kain atau pakaian dengan benang yang dirangkai menggunakan jarum rajut." },
  { term: "Ransel", definition: "Tas yang digunakan di punggung dengan dua tali bahu." },
  { term: "Raspberry", definition: "Nama warna merah muda keunguan yang dipakai dalam tren mode." },
  { term: "Ratel", definition: "Jenis kain bertekstur kasar, biasanya untuk dekorasi atau fashion etnik." },
  { term: "Rattan Bag", definition: "Tas berbahan rotan yang populer dalam tren bohemian." },
  { term: "Raw Denim", definition: "Jeans yang belum dicuci atau diproses, warnanya masih asli." },
  { term: "Rayon", definition: "Serat tekstil semi-sintetis yang halus dan ringan." },
  { term: "Reversible", definition: "Pakaian atau aksesori yang bisa dipakai bolak-balik." },
  { term: "Renda", definition: "Kain bermotif terbuka dengan sulaman halus, dipakai sebagai hiasan busana." },
  { term: "Resleting", definition: "Alat penutup pakaian berupa gigi logam atau plastik yang bisa ditarik." },
  { term: "Rib Knit", definition: "Kain rajut dengan pola garis vertikal elastis." },
  { term: "Ribbon", definition: "Pita kain untuk aksesori atau hiasan busana." },
  { term: "Rigid Denim", definition: "Denim kaku yang belum mengalami proses pelembutan." },
  { term: "Ring Belt", definition: "Sabuk dengan pengikat berbentuk cincin." },
  { term: "Ripped Jeans", definition: "Celana jeans dengan sobekan sebagai gaya kasual." },
  { term: "Rok", definition: "Pakaian bawahan wanita yang menutupi pinggang hingga kaki." },
  { term: "Rompi", definition: "Pakaian tanpa lengan yang dikenakan di bagian luar." },
  { term: "Ruffle", definition: "Hiasan kain yang dilipat berombak." },
  { term: "Rugged Look", definition: "Gaya busana yang terkesan kasar, maskulin, dan santai." },
  { term: "Runway", definition: "Panggung peragaan busana." },
  { term: "Russet", definition: "Warna cokelat kemerahan dalam palet fashion." },
  { term: "Ruched", definition: "Teknik kain yang dikumpulkan atau dirempel sehingga berlipat-lipat." },
  { term: "Rust", definition: "Warna cokelat kemerahan mirip karat, populer dalam busana vintage." },
  { term: "Rubber Sole", definition: "Sol sepatu yang terbuat dari karet." },
  { term: "Ragged Edge", definition: "Tepi kain yang dibiarkan tidak rapi sebagai efek gaya." },
  { term: "Rhinestone", definition: "Batu imitasi berkilau untuk dekorasi busana atau aksesori." },
  { term: "Romper", definition: "Pakaian one-piece pendek yang memadukan atasan dan celana pendek." },
  { term: "Rose Print", definition: "Motif kain bergambar bunga mawar." },
  { term: "Rucksack", definition: "Tas punggung bergaya klasik seperti tas gunung." },
  { term: "Racerback", definition: "Model pakaian olahraga dengan potongan tali belakang berbentuk “Y”." },
  { term: "Riding Boots", definition: "Sepatu bot panjang bergaya penunggang kuda." },
  { term: "Relaxed Fit", definition: "Potongan pakaian longgar yang nyaman." },
  { term: "Reptile Print", definition: "Motif kain menyerupai kulit ular, buaya, atau reptil lain." },
  { term: "Retro Style", definition: "Gaya busana yang terinspirasi mode masa lalu." },
  { term: "Ribbed Collar", definition: "Kerah dengan rajutan elastis bergaris." },
  { term: "Ringer Tee", definition: "Kaos dengan lis warna berbeda di leher dan lengan." },
  { term: "Round Neck", definition: "Model leher pakaian berbentuk bulat." },
  { term: "Ruffle Hem", definition: "Ujung rok atau gaun dengan lipatan bergelombang." },
  { term: "Rag Dress", definition: "Gaun dengan tampilan lusuh sebagai gaya fashion alternatif." },
  { term: "Rattan Hat", definition: "Topi berbahan rotan, sering dipakai untuk gaya bohemian." },
  { term: "Raincoat", definition: "Jas hujan berbahan tahan air." },
  { term: "Rocker Jacket", definition: "Jaket kulit dengan detail stud ala musik rock." },
  { term: "Raffled Skirt", definition: "Rok dengan lipatan-lipatan hias." },
  { term: "Robe", definition: "Pakaian panjang longgar, bisa berupa kimono atau bathrobe." },
  { term: "Ring Clutch", definition: "Tas kecil dengan pegangan cincin." },
  { term: "Reconstructed Fashion", definition: "Mode hasil daur ulang atau desain ulang pakaian lama." },
  { term: "Rivets", definition: "Paku keling kecil pada jeans atau tas untuk memperkuat jahitan dan dekorasi." },
  { term: "Satin", definition: "Satin Kain yang memiliki permukaan mengkilap dan licin di satu sisi serta kusam di sisi lainnya, sering digunakan untuk gaun malam dan pakaian elegan." },
  { term: "Scissors", definition: "Gunting Alat pemotong kain atau benang yang digunakan dalam proses menjahit." },
  { term: "Seam", definition: "Jahitan Sambungan kain yang dijahit, biasanya terdapat di bagian dalam pakaian untuk menyatukan potongan kain." },
  { term: "Seamstress", definition: "Penjahit Wanita Pekerja perempuan yang ahli membuat, memperbaiki, atau menyesuaikan pakaian." },
  { term: "Sequins", definition: "Payet Hiasan berbentuk kepingan kecil berkilau yang dijahitkan pada pakaian untuk memberikan efek gemerlap." },
  { term: "Sewing", definition: "Menjahit Proses menyatukan potongan kain menggunakan jarum dan benang." },
  { term: "Sewing machine", definition: "Mesin jahit Alat mekanis/elektrik yang digunakan untuk mempercepat proses menjahit pakaian." },
  { term: "Shirt", definition: "Kemeja Pakaian atasan dengan kerah, lengan, dan kancing di bagian depan." },
  { term: "Shaping", definition: "Pembentukan (siluet) Teknik dalam menjahit untuk membentuk pakaian agar sesuai dengan kontur tubuh." },
  { term: "Shoulder pad", definition: "Busa bahu Bantalan kecil yang diletakkan di dalam bahu pakaian untuk memberi struktur dan bentuk lebih tegas." },
  { term: "Size", definition: "Ukuran Standar dimensi pakaian, seperti kecil (S), sedang (M), besar (L), atau berdasarkan angka." },
  { term: "Sketch", definition: "Sketsa Gambar rancangan awal busana yang dibuat oleh desainer sebelum proses pembuatan." },
  { term: "Skirt", definition: "Rok Pakaian bagian bawah yang menutupi pinggang hingga paha, lutut, atau mata kaki,tanpa potongan untuk kedua kaki." },
  { term: "Sleeve", definition: "Lengan baju Bagian pakaian yang menutupi lengan, bisa bermacam-macam bentuk seperti panjang, pendek, atau tanpa lengan." },
  { term: "Snap button", definition: "Kancing jepret Jenis kancing yang bisa dipasang dan dilepas dengan cara ditekan, banyak digunakan pada jaket atau pakaian kasual." },
  { term: "Spool", definition: "Gulungan benang Silinder kecil tempat menggulung benang agar rapi dan mudah dipasang pada mesin jahit." },
  { term: "Stitch", definition: "Tusukan jahit Jejak atau bentuk yang dihasilkan dari satu kali tusukan benang dan jarum pada kain." },
  { term: "Stylist", definition: "Penata busana Orang yang mengatur, memilih, dan mengombinasikan pakaian serta aksesori agar terlihat sesuai tren atau tema tertentu." },
  { term: "Suit", definition: "Setelan jas Pakaian formal terdiri dari jas dan celana atau rok, biasanya berbahan sama." },
  { term: "Square neckline", definition: "Garis leher kotak Model potongan leher pakaian berbentuk persegi pada bagian dada." },
  { term: "Silk", definition: "Sutra Kain halus yang terbuat dari serat kepompong ulat sutra, terkenal karena kelembutan, kilauan alami, dan kenyamanannya." },
  { term: "Taffeta", definition: "Kain tenun halus dari sutra atau serat sintetis dengan kilau kaku, sering dipakai untuk gaun pesta." },
  { term: "Tailor", definition: "Orang yang ahli menjahit pakaian, terutama jas dan busana formal." },
  { term: "Tailoring", definition: "Teknik menjahit dengan presisi tinggi untuk menghasilkan busana yang rapi dan pas badan." },
  { term: "Tartan", definition: "Motif kain kotak-kotak khas Skotlandia." },
  { term: "Tank Top", definition: "Atasan tanpa lengan yang biasanya dipakai santai." },
  { term: "Tapered Pants", definition: "Celana dengan potongan yang mengecil di bagian bawah." },
  { term: "Tassel", definition: "Hiasan berupa jumbai benang yang digunakan pada aksesori atau pakaian." },
  { term: "Toga", definition: "Pakaian tradisional Romawi kuno yang dililitkan di tubuh." },
  { term: "Top Hat", definition: "Topi tinggi berbentuk silinder, sering dipakai untuk acara formal." },
  { term: "Trench Coat", definition: "Mantel panjang dengan ikat pinggang, awalnya pakaian militer Inggris." },
  { term: "Tube Dress", definition: "Gaun lurus tanpa lengan dan tanpa tali, membentuk tubuh." },
  { term: "Tunic", definition: "Atasan longgar, biasanya panjang sampai paha atau lutut." },
  { term: "Tulle", definition: "Kain jaring tipis yang ringan, sering dipakai untuk gaun pesta dan rok balerina." },
  { term: "Tuxedo", definition: "Jas formal hitam dengan satin di bagian kerah, dipakai untuk acara resmi." },
  { term: "Tie", definition: "Dasi panjang yang dililit di leher sebagai aksesori formal." },
  { term: "Tiara", definition: "Mahkota kecil berhias permata, biasa dipakai pada acara pernikahan atau kontes kecantikan." },
  { term: "Toe Cap", definition: "Bagian depan sepatu yang melindungi jari-jari kaki." },
  { term: "Tote Bag", definition: "Tas besar berbentuk persegi panjang dengan dua pegangan." },
  { term: "Track Suit", definition: "Setelan olahraga terdiri dari jaket dan celana panjang." },
  { term: "Trapeze Dress", definition: "Gaun berbentuk A-line yang longgar di bagian bawah." },
  { term: "Trimmings", definition: "Aksesori atau hiasan tambahan pada pakaian seperti renda, pita, atau payet." },
  { term: "T-Shirt", definition: "Kaos berlengan pendek dengan berbagai desain dan bahan." },
  { term: "Tank Dress", definition: "Gaun tanpa lengan dengan potongan sederhana seperti tank top." },
  { term: "T-Bar Shoes", definition: "Sepatu dengan tali berbentuk huruf T di bagian atas." },
  { term: "Turban", definition: "Penutup kepala berupa kain yang dililitkan, populer di Timur Tengah dan India." },
  { term: "Uniform", definition: "Pakaian seragam yang dikenakan oleh kelompok tertentu, misalnya sekolah, militer, atau perusahaan." },
  { term: "Unitard", definition: "Pakaian ketat satu potong yang menutupi tubuh dari bahu hingga kaki, sering dipakai penari atau atlet." },
  { term: "Umbrella Skirt", definition: "Rok berbentuk seperti payung dengan potongan lebar dan mengembang." },
  { term: "Ultra High Waist", definition: "Model celana atau rok dengan potongan pinggang sangat tinggi di atas pusar." },
  { term: "Underbust Corset", definition: "Korset yang menutupi area perut hingga bawah dada, digunakan untuk membentuk pinggang." },
  { term: "Underlay", definition: "Lapisan kain bagian dalam untuk memperkuat atau memperindah busana." },
  { term: "Undergarment", definition: "Pakaian dalam yang dikenakan di bawah pakaian utama." },
  { term: "Underwire", definition: "Kawat penyangga pada bra untuk menopang dan membentuk payudara." },
  { term: "Upcycle Fashion", definition: "Tren mengolah ulang pakaian lama menjadi busana baru yang lebih bernilai." },
  { term: "Urban Style", definition: "Gaya busana modern yang terinspirasi dari kehidupan kota, sering bernuansa streetwear." },
  { term: "Utility Jacket", definition: "Jaket dengan banyak kantong dan detail fungsional, terinspirasi dari pakaian kerja." },
  { term: "Utility Pants", definition: "Celana dengan banyak saku praktis, mirip dengan cargo pants." },
  { term: "Ultra-Light Fabric", definition: "Bahan kain yang sangat ringan, biasanya digunakan untuk busana musim panas." },
  { term: "Ultra Violet", definition: "Warna tren dalam fashion, ungu kebiruan yang elegan." },
  { term: "Uneven Hem", definition: "Potongan bawah pakaian yang tidak simetris, memberi efek unik." },
  { term: "Unisex Fashion", definition: "Busana yang bisa dikenakan baik oleh pria maupun wanita." },
  { term: "Unstructured Jacket", definition: "Jaket tanpa padding atau struktur kaku, memberi kesan lebih kasual." },
  { term: "Upskirt", definition: "Potongan rok atau gaun yang lebih pendek" },
  { term: "Uptown Style", definition: "Gaya busana elegan dan glamor khas kehidupan kota besar." },
  { term: "Unbuttoned Shirt", definition: "Kemeja yang dipakai dengan kancing terbuka, biasanya untuk gaya santai." },
  { term: "Ultra Mini Skirt", definition: "Rok dengan panjang sangat pendek di atas paha." },
  { term: "Utility Vest", definition: "Rompi fungsional dengan banyak kantong, populer di streetwear." },
  { term: "Under Collar", definition: "Bagian bawah kerah pakaian yang kadang diberi warna atau bahan berbeda sebagai detail desain." },
  { term: "Velvet", definition: "Kain mewah dengan permukaan lembut berbulu pendek, sering dipakai untuk gaun pesta." },
  { term: "Vest", definition: "Rompi tanpa lengan yang bisa dipakai formal maupun kasual." },
  { term: "Vintage Fashion", definition: "Gaya busana yang terinspirasi dari mode era lama (20–100 tahun lalu)." },
  { term: "V-Neck", definition: "Potongan leher pakaian berbentuk huruf V." },
  { term: "V-Neck Dress", definition: "Gaun dengan potongan leher berbentuk V." },
  { term: "V-Back Dress", definition: "Gaun dengan potongan punggung berbentuk V." },
  { term: "Velvet Boots", definition: "Sepatu boots berbahan beludru yang memberi kesan glamor." },
  { term: "Velvet Blazer", definition: "Blazer berbahan beludru, populer untuk acara malam.Velvet Skirt : Rok berbahan beludru yang elegan." },
  { term: "Viscose", definition: "Serat tekstil semi-sintetis yang lembut dan menyerupai sutra." },
  { term: "Vamp (Shoes)", definition: "Bagian atas sepatu yang menutupi punggung kaki." },
  { term: "Varsity Jacket", definition: "Jaket bergaya kampus Amerika dengan huruf besar di dada." },
  { term: "Voluminous Skirt", definition: "Rok dengan potongan lebar dan mengembang." },
  { term: "Volume Sleeves", definition: "Lengan pakaian yang dibuat mengembang dengan teknik tertentu." },
  { term: "Viscose Blend", definition: "Bahan campuran viscose dengan serat lain untuk kenyamanan." },
  { term: "Velvet Choker", definition: "Kalung berbahan beludru yang populer di era 1990-an." },
  { term: "Velvet Pants", definition: "Celana berbahan beludru dengan nuansa klasik." },
  { term: "Vent (Tailoring)", definition: "Belahan pada jas atau rok untuk memberi kelonggaran gerak." },
  { term: "Varnished Leather", definition: "Kulit yang dipoles hingga mengilap, dipakai pada sepatu atau tas." },
  { term: "Vegan Leather", definition: "Bahan imitasi kulit yang ramah lingkungan, tidak menggunakan hewan." },
  { term: "Velcro", definition: "Perekat tekstil dengan sistem kait dan loop, digunakan pada sepatu atau pakaian." },
  { term: "Visor", definition: "Penutup kepala dengan bagian depan pelindung matahari tanpa penutup belakang." },
  { term: "Velvet Gown", definition: "Gaun berbahan beludru yang mewah untuk acara formal." },
  { term: "Velvet Handbag", definition: "Tas berbahan beludru dengan kesan elegan." },
  { term: "Velvet Cape", definition: "Jubah atau cape berbahan beludru, sering dipakai untuk fashion klasik." },
  { term: "Waistband", definition: "Bagian pinggang pada celana atau rok yang berfungsi menahan pakaian tetap pas di tubuh." },
  { term: "Waistcoat", definition: "Rompi formal yang biasanya dipakai di dalam jas." },
  { term: "Waistline", definition: "Garis potongan pakaian yang menunjukkan letak pinggang." },
  { term: "Wrap Dress", definition: "Gaun yang dililitkan dan diikat pada pinggang, populer oleh Diane von Fürstenberg." },
  { term: "Wrap Skirt", definition: "Rok lilit yang dipasang dengan ikatan atau kancing." },
  { term: "Wool", definition: "Serat tekstil alami yang berasal dari bulu domba." },
  { term: "Woolen", definition: "Bahan tekstil berbulu lembut yang dibuat dari wol." },
  { term: "Woven Fabric", definition: "Kain tenun yang dibuat dengan teknik silang antara benang pakan dan lusi." },
  { term: "Wing Collar", definition: "Model kerah kemeja dengan ujung runcing ke bawah, dipakai untuk acara formal." },
  { term: "Wide-Leg Pants", definition: "Celana dengan potongan lebar dari pinggang hingga ujung kaki." },
  { term: "Wedge Heels", definition: "Model sepatu dengan hak tebal menyatu dari tumit hingga telapak." },
  { term: "Western Wear", definition: "Gaya busana koboi khas Amerika Barat, dengan topi cowboy, boots, dan kemeja kotak-kotak." },
  { term: "Wristband", definition: "Aksesori yang dipakai di pergelangan tangan, bisa berupa kain, kulit, atau karet." },
  { term: "Watch Cap", definition: "Topi rajut sederhana yang menutupi kepala, mirip beanie." },
  { term: "Waterproof Fabric", definition: "Bahan kain tahan air yang digunakan untuk jas hujan atau jaket outdoor." },
  { term: "Windbreaker", definition: "Jaket ringan tahan angin dan hujan." },
  { term: "Worker Jacket", definition: "Jaket kerja fungsional dengan banyak saku, populer di fashion utilitarian." },
  { term: "Wrap Coat", definition: "Mantel yang dipakai dengan cara dililitkan dan diikat di pinggang." },
  { term: "Wasp Waist", definition: "Bentuk pinggang sangat ramping yang dihasilkan dari penggunaan korset." },
  { term: "Winter Coat", definition: "Mantel tebal yang dipakai pada musim dingin." },
  { term: "Wool Coat", definition: "Mantel berbahan wol yang hangat dan elegan." },
  { term: "Waist Cincher", definition: "Korset pendek yang dipakai untuk mengecilkan pinggang." },
  { term: "Woven Bag", definition: "Tas yang dibuat dari anyaman bahan alami atau sintetis." },
  { term: "Waist Tie", definition: "Ikat pinggang kain yang digunakan sebagai detail busana." },
  { term: "White Tie", definition: "Dress code paling formal dengan frak, rompi putih, dan dasi kupu-kupu putih." },
  { term: "Workwear", definition: "Pakaian kerja fungsional yang kini banyak diadaptasi ke fashion streetwear." },
  { term: "Wardrobe", definition: "Koleksi pakaian yang dimiliki seseorang." },
  { term: "Wool Blend", definition: "Bahan kain campuran wol dengan serat lain." },
  { term: "Wrap Top", definition: "Atasan dengan potongan lilit yang diikat di pinggang atau samping." },
  { term: "Waffle Fabric", definition: "Kain dengan tekstur timbul kotak-kotak kecil seperti wafel, sering dipakai untuk handuk atau loungewear." },
  { term: "X-back", definition: "Gaya pakaian dengan desain X di bagian belakang." },
  { term: "X-large", definition: "Ukuran pakaian yang sangat besar." },
  { term: "X-stitch", definition: "Jenis jahitan yang membentuk pola X." },
  { term: "Xenial", definition: "Gaya yang elegan dan mewah." },
  { term: "X-ray print", definition: "Desain cetak yang menyerupai hasil X-ray." },
  { term: "X-treme fashion", definition: "Gaya fashion yang ekstrem dan berani." },
  { term: "X-line dress", definition: "Dress dengan bentuk yang menyerupai huruf X." },
  { term: "X-outfit", definition: "Outfit dengan desain yang unik dan berani." },
  { term: "X-pattern", definition: "Polusi dengan bentuk X." },
  { term: "X-style", definition: "Gaya fashion yang unik dan trendi." },
  { term: "X-tend", definition: "Memperpanjang atau memperluas desain fashion." },
  { term: "X-factor", definition: "Faktor yang membuat fashion menjadi lebih menarik." },
  { term: "Xclusive", definition: "Eksklusif dan mewah." },
  { term: "Xenon-inspired", definition: "Desain yang terinspirasi dari gas Xenon." },
  { term: "Xanadu", definition: "Gaya yang mewah dan elegan." },
  { term: "Xanthous", definition: "Warna yang cerah dan mencolok." },
  { term: "X-ray vision", definition: "Desain yang transparan dan futuristik." },
  { term: "X-caps", definition: "Topi dengan desain X." },
  { term: "X-treme accessories", definition: "Aksesoris yang ekstrem dan berani." },
  { term: "X-fusion", definition: "Perpaduan gaya fashion yang unik dan menarik." },
  { term: "Xquisite", definition: "Desain yang sangat detail dan elegan." },
  { term: "Xenophobia-free fashion", definition: "Fashion yang bebas dari diskriminasi budaya." },
  { term: "X-chromosome chic", definition: "Gaya fashion yang feminin dan elegan." },
  { term: "X-rated fashion", definition: "Fashion yang berani dan provokatif." },
  { term: "X-treme textures", definition: "Tekstur yang ekstrem dan unik dalam fashion." },
  { term: "X-height heels", definition: "Sepatu hak tinggi dengan desain yang unik." },
  { term: "X-ray eyes", definition: "Desain yang memiliki detail yang sangat tajam." },
  { term: "X-tra large", definition: "Ukuran yang sangat besar dan mewah." },
  { term: "X-tra special", definition: "Desain yang sangat unik dan spesial." },
  { term: "Xylophone-inspired fashion", definition: "Desain fashion yang terinspirasi dari xilofon." },
  { term: "Xenogamy", definition: "Perpaduan gaya fashion dari berbagai budaya." },
  { term: "Xenial style", definition: "Gaya yang elegan dan mewah." },
  { term: "X-treme sportswear", definition: "Pakaian olahraga yang ekstrem dan berani." },
  { term: "X-ray art", definition: "Desain seni yang menyerupai hasil X-ray." },
  { term: "X-fect", definition: "Desain yang sempurna dan tanpa cela." },
  { term: "X-cessive", definition: "Desain yang berlebihan dan mewah." },
  { term: "X-treme colors", definition: "Warna yang ekstrem dan mencolok." },
  { term: "Xenial fashion", definition: "Fashion yang elegan dan mewah." },
  { term: "X-ray fashion", definition: "Desain fashion yang menyerupai hasil X-ray." },
  { term: "X-treme fashionista", definition: "Orang yang memiliki gaya fashion yang ekstrem dan berani." },
  { term: "Xquisite detailing", definition: "Detail yang sangat halus dan elegan." },
  { term: "Xenon lights", definition: "Desain yang terinspirasi dari lampu Xenon." },
  { term: "X-treme streetwear", definition: "Pakaian streetwear yang ekstrem dan berani." },
  { term: "X-fusion style", definition: "Perpaduan gaya fashion yang unik dan menarik." },
  { term: "X-traordinary", definition: "Desain yang sangat unik dan luar biasa." },
  { term: "Xenophobia-free style", definition: "Gaya yang bebas dari diskriminasi budaya." },
  { term: "X-chic", definition: "Gaya yang feminin dan elegan." },
  { term: "X-treme luxury", definition: "Kemewahan yang ekstrem dan berani." },
  { term: "X-ray visionary", definition: "Desain yang memiliki visi yang tajam dan futuristik." },
  { term: "X-treme glamour", definition: "Glamor yang ekstrem dan berani." },
  { term: "Yoke", definition: "Potongan kain di bagian atas pakaian (pada bahu atau pinggang) untuk memberi bentuk." },
  { term: "Yarn", definition: "Benang yang digunakan dalam proses menenun atau merajut kain." },
  { term: "Yoke Dress", definition: "Gaun dengan potongan tambahan di bagian dada atau bahu." },
  { term: "Yoke Skirt", definition: "Rok dengan potongan yoke di bagian pinggang untuk memberi bentuk lebih rapi." },
  { term: "Yellow Gold", definition: "Warna emas kekuningan yang sering dipakai dalam aksesori fashion." },
  { term: "Yoga Pants", definition: "Celana ketat elastis yang nyaman, dipakai untuk yoga atau olahraga ringan." },
  { term: "Yuppie Style", definition: "Gaya busana khas eksekutif muda era 1980-an, rapi dan profesional." },
  { term: "Y-Back Tank", definition: "Atasan tank top dengan tali berbentuk huruf Y di bagian belakang." },
  { term: "Y-Front Briefs", definition: "Celana dalam pria dengan potongan berbentuk huruf Y di bagian depan." },
  { term: "Youth Fashion", definition: "Tren busana yang identik dengan remaja, biasanya kasual dan trendi." },
  { term: "Y-Neckline", definition: "Potongan kerah berbentuk huruf Y pada atasan atau gaun." },
  { term: "Yarn-Dyed Fabric", definition: "Kain yang diberi warna pada benangnya sebelum ditenun." },
  { term: "Yellow Hue", definition: "Warna kuning dalam berbagai gradasi yang sering dipakai di fashion musim panas." },
  { term: "Y-Strap Sandals", definition: "Sandal dengan tali berbentuk huruf Y, mirip flip-flop." },
  { term: "Yarn Embroidery", definition: "Teknik sulaman menggunakan benang rajut atau benang tebal." },
  { term: "Yogi Style", definition: "Gaya busana santai terinspirasi dari pakaian untuk yoga." },
  { term: "Y-Shaped Back Bra", definition: "Model bra dengan tali berbentuk huruf Y di belakang." },
  { term: "Yak Wool", definition: "Bahan kain yang dibuat dari bulu yak, hangat dan lembut." },
  { term: "Yuppie Look", definition: "Tampilan formal modern dengan jas, dasi, dan aksesori elegan." },
  { term: "Youth Subculture Style", definition: "Gaya busana khas komunitas muda tertentu (punk, hip-hop, goth)." },
  { term: "Y-Chain Necklace", definition: "Kalung panjang dengan gantungan berbentuk huruf Y." },
  { term: "Yellow Sapphire", definition: "Batu permata kuning yang digunakan dalam perhiasan fashion." },
  { term: "Y-Neck Cardigan", definition: "Cardigan dengan potongan kerah berbentuk huruf Y." },
  { term: "Y-Front Swimwear", definition: "Celana renang pria dengan potongan depan berbentuk Y." },
  { term: "Yarn Weaving", definition: "Teknik tenun menggunakan benang sebagai bahan utama." },
  { term: "Y-Dye Technique", definition: "Teknik pewarnaan kain dengan pola berbentuk huruf Y." },
  { term: "Youthful Style", definition: "Gaya busana yang memberi kesan muda, segar, dan energik." },
  { term: "Y-Strap Dress", definition: "Gaun dengan tali berbentuk Y di bagian belakang." },
  { term: "Yew Green", definition: "Warna hijau tua seperti daun pohon yew, sering dipakai di fashion autumn." },
  { term: "Yoke Blouse", definition: "Blus dengan tambahan potongan yoke di bagian dada atau bahu untuk aksen desain." },
  { term: "Zipper", definition: "Ritsleting, alat penutup pakaian atau aksesori yang terdiri dari dua sisi gigi logam/plastik." },
  { term: "Zoot Suit", definition: "Setelan longgar dengan celana sangat lebar dan jas panjang, populer tahun 1940-an." },
  { term: "Zigzag Stitch", definition: "Jahitan zigzag yang dipakai untuk mengunci tepi kain agar tidak mudah terurai." },
  { term: "Zebra Print", definition: "Motif kain bermotif belang hitam putih menyerupai kulit zebra." },
  { term: "Zipped Jacket", definition: "Jaket dengan penutup utama menggunakan ritsleting." },
  { term: "Zip Hoodie", definition: "Jaket berkupluk dengan ritsleting di bagian depan." },
  { term: "Zip Dress", definition: "Gaun dengan detail ritsleting sebagai bukaan atau dekorasi." },
  { term: "Zip-Off Pants", definition: "Celana dengan bagian bawah yang bisa dilepas menggunakan ritsleting (jadi celana pendek)." },
  { term: "Zipped Boots", definition: "Sepatu boots dengan ritsleting di samping atau belakang." },
  { term: "Zibeline", definition: "Kain wol mewah dengan tekstur halus dan mengkilap, biasanya untuk mantel." },
  { term: "Zori", definition: "Sandal tradisional Jepang yang terbuat dari jerami, kayu, atau bahan sintetis." },
  { term: "Zulu Beads", definition: "Aksesori tradisional suku Zulu dari Afrika Selatan, berupa manik-manik berwarna-warni." },
  { term: "Zero Waste Fashion", definition: "Konsep fashion berkelanjutan tanpa menyisakan limbah kain dalam prouksi." },
  { term: "Zigzag Pattern", definition: "Pola desain kain atau rajutan dengan motif bergelombang zigzag." },
  { term: "Zip Clutch", definition: "Tas kecil dengan penutup ritsleting." },
  { term: "Zip Pocket", definition: "Kantong pakaian yang ditutup dengan ritsleting." },
  { term: "Zipped Skirt", definition: "Rok dengan detail ritsleting, baik sebagai bukaan maupun dekorasi." },
  { term: "Zip-Up Sweater", definition: "Sweater yang memiliki bukaan ritsleting di depan." },
  { term: "Zigzag Hem", definition: "Potongan bawah pakaian yang berbentuk bergerigi zigzag." },
  { term: "Zipper Puller", definition: "Kepala ritsleting yang digunakan untuk menarik buka-tutup." },
  { term: "Zipped Jumpsuit", definition: "Jumpsuit dengan bukaan utama menggunakan ritsleting." },
  { term: "Zip Pouch", definition: "Dompet kecil atau kantong aksesoris dengan ritsleting." },
  { term: "Zipped Handbag", definition: "Tas tangan dengan bukaan ritsleting." },
  { term: "Zipped Wallet", definition: "Dompet dengan penutup ritsleting agar lebih aman." },
  { term: "Zardozi", definition: "Bordir tradisional India yang menggunakan benang emas atau perak dengan desain rumit." },
].sort((a, b) => a.term.localeCompare(b.term, 'id')); // Mengurutkan data berdasarkan abjad